### ISSUE TITLE
OLMo-3-1025-7B midtraining: multiple issues when resuming from checkpoint

### ISSUE THREAD

**Issue by sbordt** [allenai/OLMo-core#617]
# OLMo-3-1025-7B midtraining: multiple issues when resuming from checkpoint

I have had some problems with OLMo-3-1025-7B midtraining.

I'm trying to continue training from the checkpoint at gradient step 10000. I'm using the main branch of OLMo-core, and try to run the command:

```bash
torchrun --nproc_per_node=4 --master_port=29501 OLMo-3-1025-7B-midtrain.py \
  --save-folder=[...] \
  trainer.load_path=[...]/OLMo-3-1025-7B-midtrain-1/step10000 \
  trainer.load_trainer_state=true \
  trainer.hard_stop={value: 10100, unit: steps} \
  trainer.metrics_collect_interval=1 \
  trainer.callbacks.wandb.enabled=true \
  train_module.rank_microbatch_size=8192
```

The first error that I get is that the file `OLMo-midtraining-mix-0725-100B.txt` does not exist, which I think is just a typo in the current repo where it says:

```python
# Midtraining mixes
OLMo_midtraining_mix_0625_100B = "OLMo-midtraining-mix-0725-100B"
```

After fixing this typo, the training script crashes with the error that the dataset fingerprint does not match.

So I set `data_loader.ignore_fingerprint_mismatch=true`, and now training performs one gradient step, but then it repeatedly crashes with a CUDA error:

<details>
<summary>CUDA error stack trace</summary>

```
Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x80 (/usr/local/lib/python3.12/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x11fb7 (/usr/local/lib/python3.12/dist-packages/torch/lib/libc10_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x50 (/usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x68 (/usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::Watchdog::runLoop() + 0x969 (/usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::Watchdog::run() + 0xdf (/usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0xecdb4 (/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x9ca94 (/lib/x86_64-linux-gnu/libc.so.6)
frame #8: __clone + 0x44 (/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG ID 2 PG GUID 5(mesh_dp_shard) Rank 2] Process group watchdog thread terminated with exception: CUDA error: device-side assert triggered
```

</details>

In contrast, pretraining with `OLMo-3-1025-7B-pretrain-1.py` works fine for me.

Appreciate any feedback,
Sebastian

**Comment by baileykuehl** [comment]
Hi @sbordt, thanks for reaching out! 

Regarding your first issue with the typo - good catch, thanks for pointing this out! This should now be fixed in the main branch. 

Regarding the `CUDA error: device-side assert triggered` - we did some investigating and it looks like there was a small issue with the format of those midtraining data files (they had an unexpected header at the beginning because of how they were saved which was causing issues with token id values when loading in). I fixed and reuploaded that data and then launched `OLMo-3-1025-7B-midtrain.py` to make sure that resolved it. I ran through about ~50 training steps and all looks good on my end now, but please let me know if you're still having issues!

**Comment by sbordt** [comment]
Thanks for fixing this so quickly @baileykuehl  ! It works on my end now as well :)
